# Generated by Django 4.2.2 on 2023-06-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
