# Generated by Django 4.2.2 on 2023-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
