# Generated by Django 4.2.2 on 2023-06-30 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_hostel_alter_customuser_hostel'),
        ('dashboard', '0003_complaint_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='authentication.studentuser'),
        ),
    ]
