# Generated by Django 4.2.2 on 2023-07-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_studentuser_department_studentuser_faculty'),
        ('dashboard', '0004_alter_complaint_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.hostel'),
        ),
    ]
