# Generated by Django 4.2.2 on 2023-06-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='matric_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
