# Generated by Django 4.2.2 on 2023-06-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_studentuser_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Professor Biobaku Hall', 'Professor Biobaku Hall'), ('Queen Amina Hall', 'Queen Amina Hall'), ('King Jaja Hall', 'King Jaja hall')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
