# Generated by Django 4.2.2 on 2023-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_studentuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porteruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='porteruser',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='porteruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hostel',
            field=models.CharField(blank=True, choices=[('Professor Biobaku Hall', 'Professor Biobaku Hall'), ('Queen Amina Hall', 'Queen Amina Hall'), ('King Jaja Hall', 'King Jaja hall')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
