# Generated by Django 4.2.2 on 2023-06-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_is_porter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='matric_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
