# Generated by Django 4.2.2 on 2023-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_studentuser_matric_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='block_no',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='room_no',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
