# Generated by Django 4.2.2 on 2023-06-30 22:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_studentuser_block_no_studentuser_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Professor Biobaku Hall', 'Professor Biobaku Hall'), ('Queen Amina Hall', 'Queen Amina Hall'), ('King Jaja Hall', 'King Jaja hall')], max_length=100)),
                ('no_of_rooms', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hostel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.hostel'),
        ),
    ]
