# Generated by Django 4.2.2 on 2023-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_porteruser_updated_at_studentuser_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
