# Generated by Django 4.2.2 on 2023-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matric_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
