# Generated by Django 4.2.2 on 2023-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_customuser_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(choices=[('Professor Biobaku Hall', 'Professor Biobaku Hall'), ('Queen Amina Hall', 'Queen Amina Hall'), ('King Jaja Hall', 'King Jaja hall'), ('Osun block', 'Osun block'), ('Ondo block', 'Ondo block'), ('Calabar block', 'Calabar block'), ('Anthony block', 'Anthony block'), ('Ekiti block', 'Ekiti block'), ('Oyo block', 'Oyo block'), ('Kwara block', 'Kwara block'), ('Kogi block', 'Kogi block'), ('Block A', 'Block A'), ('Block B', 'Block B'), ('Block C', 'Block C'), ('Block D', 'Block D'), ('Block NH', 'Block NH'), ('Block AKB', 'Block AKB'), ('Block AKB Anex', 'Block AKB Anex')], max_length=100),
        ),
    ]
