# Generated by Django 4.2.2 on 2023-11-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_studentuser_department_studentuser_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.hostel'),
        ),
    ]
